# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23d6c3148e78d6b261cf0fee7ce927c1025f937e18d2965983514e97a9e2aa5a8cb0f5aa7a28e89335dba7a07a6ba96c66802e49ab4650875f23593d5bb24e21

test:
  secret_key_base: 2beabaf0d608086aad85a0c70a307ca9d6683170ce43989c2b9e21dcefa9d5b5d267175aa2ce609c85383a4a72a43315c24bac98d772a5d58c5f1ae23cfb00d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
